# ndarray의 주요 기능
## 타입 지정

In [2]:
import numpy as np

In [3]:
# dtype 파라미터를 사용한 강제 타입 지정
# int, float 가 대부분

mylist1 = [100.12, 3.14, 1.5]
myarr1 = np.array(mylist1, dtype = 'int')
myarr1

array([100,   3,   1])

### 문자열이 포함된 경우의 형변환

In [4]:
# 모든 프로그래밍 언어에서 문자열은 표현범위가 가장 넓은 타입

mylist2 = [1.2, 3, True, '4']
myarr2 = np.array(mylist2)
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

### list 타입으로 역변환

In [5]:
# ndarray와 list는 서로 호환 가능

mylist3 = [10, 20, 30, 40, 50]
myarr3 = np.array(mylist3)
print(type(myarr3), myarr3)

mylist3_1 = list(myarr3)
print(type(mylist3_1), mylist3_1)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


### 연산자를 사용한 ndarray 연산

In [ ]:
# 위치가 동일한 원소끼리 연산을 수행한다

arr1 = np.array([10, 15, 20, 25, 30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)
print('-' * 50)
a = arr1 + arr2
print(a)

b = arr1 * arr2
print(b)

c = arr1 / arr2
print(c)

d = arr1 - arr2
print(d)

[10 15 20 25 30]
[2 3 4 5 6]
--------------------------------------------------
[12 18 24 30 36]
[ 20  45  80 125 180]
[5. 5. 5. 5. 5.]
[ 8 12 16 20 24]


### 조건에 맞는 위치의 원소 추출


In [20]:
import numpy as np

In [22]:
# 철수의 1학년~4학년까지의 평균 점수

grade = np.array([82, 77, 91, 88])
grade

# 추출하고자 하는 원본과 같은 사이즈의 배열 생성
# 추출할 값은 True, 이외의 값은 False

bool_array = np.array([True, False, True, False])

# 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
result1

array([82, 91])

### 조건식에 따른 원소 추출

In [26]:
# 80점 이상 원소만 추출
# 조건 명시위해 배열의 이름이 조건식에 명시된다.

mypoint = np.array([82, 77, 91, 88])
a = mypoint[mypoint >=80]
print(a)

b = mypoint[np.logical_and(mypoint >=80, mypoint <=90)]
print(b)

c = mypoint[np.logical_or(mypoint <80, mypoint >90)]
print(c)

[82 91 88]
[82 88]
[77 91]


### Numpy의 조건 연산

In [27]:
# SQL IF문과 동일한 결과

exam = np.array([60, 83, 75, 92, 86])

# 조건 참 = True 이외 False

result = np.where(exam >= 80, '합격', '불합격')
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

### 여러 조건을 한 번에 처리하기

In [31]:
exam = np.array([60, 85, 51, 79, 94, 88])

# 학점 부여 위한 점수 구간을 설정하는 조건들을 리스트로 설정
conditions = [(exam >= 90),
              (exam >= 80),
              (exam >= 70)
]

# 조건에 따라 부여될 학점
value = ['A','B','C']

#조건과 조건을 판단하기 위한 값을 지정
# default는 조건에 맞는 값이 아닌 경우 사용됨 (생략 가능)

result = np.select(conditions, value, default ='F')
result

array(['F', 'B', 'F', 'C', 'A', 'B'], dtype='<U1')

### 연습문제

In [ ]:
# 1번 문제
score = [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]
myarr1 = np.array(score, dtype = 'int')
print('원본 점수:', myarr1)

원본 점수: [72 88 91 67 80 59]


In [38]:
# 2번 문제

score = np.array([72.5, 88.0, 91.5, 67.0, 80.0, 59.5])
a = mypoint[mypoint >=80]
print('80 점 이상:', a)

80 점 이상: [82 91 88]


In [ ]:
# 3번 문제

score = np.array([72.5, 88.0, 91.5, 67.0, 80.0, 59.5])

conditions = [(score >= 90),
              (score >= 80),
              (score >= 70)
]
Values = ['A','B','C']

result = np.select(conditions, Values, default ='F')
print('학점 결과:',result)

학점 결과: ['C' 'B' 'A' 'F' 'B' 'F']
