# 그 밖의 ndarray 형태
## 라이브러리 참조하기

In [1]:
import numpy as np

### 2차원 배열

In [2]:
# 2차원 리스트를 ndarray로 변환한다

myarray = np.array([
    [98, 72, 80, 64],
    [88, 90, 80, 72],
    [92, 88, 82, 76]
])

print(myarray)

print('차원크기:', myarray.ndim)
print('차원별 원소수', myarray.shape)
print('원소의 데이터 타입', myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기: 2
차원별 원소수 (3, 4)
원소의 데이터 타입 int64


### boolean 타입으로 인덱싱

In [4]:
# 조건에 맞는 원소를 '1차원 배열'로 반환

bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

# 조건에 맞는 항목(True 값)을 1차 배열로 추출
result = myarray[bool_array]
result

array([98, 80, 88, 90, 80, 92, 88, 82])

### 정형화된 배열 생성

In [15]:
# 모든 원소가 0인 배열
print(np.zeros([3,4]))
print('-'*50)
# 모든 원소가 1인 배열
print(np.ones([3,4]))
print('-'*50)
# 모든 원소가 특정 값인 배열
print(np.full([3,4], 10))
print('-'*50)
# 대각선 원소가 1, 그 외에는 0인 배열
print(np.eye(4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
--------------------------------------------------
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
--------------------------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 랜덤 배열(1)


In [21]:
# 0~1 범위에서 균등하게 추출하여 N차원 랜덤 배열 생성
# 10개의 값을 가지는 1차원 배열
#np.random.rand(10)

# 4행 3열의 값을 가지는 1차원 랜덤 배열
np.random.rand(4,3)

array([[0.15529872, 0.99172774, 0.3914982 ],
       [0.26771623, 0.97452983, 0.46534143],
       [0.53927044, 0.19128733, 0.51180643],
       [0.99499029, 0.31960181, 0.41790388]])

### 주어진 범위 안에서 정수값을 갖는 랜덤 배열


In [30]:
# 0~9사이 랜덤값 10개의 원소를 갖는 1차원 배열 --> 중복 존재

# np.random.rand(0,9,10) --> 이렇게 값 입력시 다르게 나옴!
np.random.randint(0, 9, 10)
# np.random.randfloat(0,9,10) --> 존재하지 않는 모듈이라 나옴

# 0~9사이 랜덤값 10개의 원소를 갖는 3행 4열의 2차원 배열
np.random.randint(0,9,(3,4))

array([[6, 7, 0, 4],
       [7, 2, 0, 7],
       [1, 7, 3, 3]], dtype=int32)

### 랜덤 시드 고정


In [33]:
# 랜덤 시드

np.random.seed(1234)
np.random.normal(0,1,(3,4))

array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294,  0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495,  1.15003572,  0.99194602]])

### 표준 정규 분포를 따르는 랜덤 배열

In [ ]:
# 원소가 10개인 1차원 배열
# 이 매서드 함수 자체가 평균 = 0, 분산 = 1 을 따른다는 가정이 들어간 상태.
np.random.randn(10)

# 원소가 12개인 4행 3열의 2차원 배열

np.random.randn(4,3)

array([[ 1.04757857,  1.04593826,  0.86371729],
       [-0.12209157,  0.12471295, -0.32279481],
       [ 0.84167471,  2.39096052,  0.07619959],
       [-0.56644593,  0.03614194, -2.0749776 ]])

### 연습 문제

In [ ]:
# 1번 문제

array = np.random.seed(100)
#np.random.randn(3,4)
array_normal = np.random.normal(75,5,[3,4]) #--> [] 튜플형식 나 () 리스트 형식 둘 다 상관없음
array_normal

array([[66.25117263, 76.71340202, 80.76517901, 73.73781982],
       [79.90660393, 77.57109421, 76.10589835, 69.64978335],
       [74.05252085, 76.27500722, 72.70986507, 77.17581744]])

In [ ]:
# 2번 문제

result = array_normal[array_normal >= 80]
result

array([80.76517901])

In [48]:
# 3번 문제

print('차원크기:', array_normal.ndim)
print('형태:', array_normal.shape)
print('데이터 타입:', array_normal.dtype)

차원크기: 2
형태: (3, 4)
데이터 타입: float64
