# ndarray 형태 변환 
## NumPy 라이브러리

### 원소의 데이터 타입 변환 - 1 astype() 함수 사용

In [1]:
import numpy as np

In [3]:
# 0~10 전까지 1씩 증가하는 원소를 갖는 배열 생성
arr1 = np.arange(10)
print('원본배열:', arr1)
print('원본배열의 데이터 타입:', arr1.dtype)

원본배열: [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입: int64


In [ ]:
#arr2 = arr1.astype('float')
#print('형변환 후 배열:', arr2)
#print('변환된 배열의 데이터 타입:', arr2.dtype)

형변환 후 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


In [7]:
arr1 = np.arange(10, 20)
print('원본배열:', arr1)
print('원본배열의 데이터 타입:', arr1.dtype)

원본배열: [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입: int64


In [11]:
# 실수 타입으로 변환
arr2 = np.asarray(arr1, dtype ='float')
print('원본배열:', arr2)
print('원본배열의 데이터 타입:', arr2.dtype)

원본배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
원본배열의 데이터 타입: float64


In [12]:
arr2 = np.asarray(arr1, dtype = 'str')
print('원본배열:', arr2)
print('원본배열의 데이터 타입:', arr2.dtype)

원본배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
원본배열의 데이터 타입: <U21


### 차원변환 -reshape() 함수

In [13]:
# 1~20전까지 1씩 증가하는 1차원 배열 생성

origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 1차원 배열을 4행 5열의 2차원 배열로 전환
# arange값이 20 이므로, 이 값에 맞춘 배열을 뽑아내야 한다. 아님 에러 뜬다.
a = origin.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 차원 축소 - reshape() 함수

In [18]:
# 원본 배열
origin = np.array([
    [0,1,2,3,4],
    [5,6,7,8,9],
    [10,11,12,13,14],
    [15,16,17,18,19]
])
origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
# 1차 배열로 축소하기
a = origin.reshape(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
# 원소 계산 후 1차원 배열로 축소하기
rows,cols = origin.shape
rows,cols

b = origin.reshape(rows * cols)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### reshape() 함수에서 -1의 의미

In [24]:
# 기존 차원에서 -1 빼라는 뜻으로 이해

origin =np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])
origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
z = origin.reshape(-1,1)
z

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [27]:
x = origin.reshape(1,-1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [28]:
c = origin.reshape(-1,2)
c

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
# reshape(-1)일 때는, 1차원 배열로 변환
v = origin.reshape(-1)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 연습문제

In [66]:
# 1번 문제
arr1 = np.arange(12)
print('원본 배열:', arr1)

원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [68]:
# 2번 문제
#a = arr1.astype('float')
#a
# 다른 방법
a = np.asarray(arr1, dtype = 'float')
print('실수형 변환:', a)

실수형 변환: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [74]:
# 3번 문제

b = a.reshape(2,6)
print('2행 6열 형태:\n', b)

2행 6열 형태:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]


In [75]:
# 4번 문재

c = b.reshape(3,-1)
print('자동 계산된 형태:\n', c)

자동 계산된 형태:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [76]:
# 5번 문제

d = c.reshape(-1)
print('1차원 배열로 축소:', d)

1차원 배열로 축소: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
