### 기초 통계량의 이해 - 2

In [1]:
# 라이브러리 참조
import numpy as np

### 샘플 데이터 준비

In [3]:
# 학급 시험 점수
point = np.array([100, 91, 89, 86, 84, 79, 78, 77, 74, 71, 69, 66, 65, 60, 58, 57, 55])
point

array([100,  91,  89,  86,  84,  79,  78,  77,  74,  71,  69,  66,  65,
        60,  58,  57,  55])

### Numpy의 histogram: 도수 분포표 - 1


In [5]:
# 5개 구간으로 나누기
hist, bins = np.histogram(point, 5)
print('구간별 데이터 수:', hist)
print('구간 경계:', bins)

구간별 데이터 수: [4 4 4 3 2]
구간 경계: [ 55.  64.  73.  82.  91. 100.]


### Numpy의 histogram: 도수 분포표 - 2


In [8]:
# 도수 분포표 구성
s = len(hist)
for i in range(0, s):
    if i+1 <s:
        tpl = '%d이상 %d미만: %d개'
    else:
        tpl = '%d이상 %d이하: %d개'
    print(tpl % (bins[i], bins[i+1], hist[i]))

55이상 64미만: 4개
64이상 73미만: 4개
73이상 82미만: 4개
82이상 91미만: 3개
91이상 100이하: 2개


### Numpy의 histogram: 도수 분포표 - 3

In [9]:
# 데이터 구간 직접 정의하기

hist, bins = np.histogram(point, [50,60,70,80,90,100])
print('구간별 데이터 수:', hist)
print('구간 경계:', bins)

구간별 데이터 수: [3 4 5 3 2]
구간 경계: [ 50  60  70  80  90 100]


### 도수의 종류


In [ ]:
# 상대도수
relative_freq = hist / np.sum(hist)
relative_freq

array([0.17647059, 0.23529412, 0.29411765, 0.17647059, 0.11764706])

In [14]:
# 누적 도수

Sum_freq = []

previous = 0

for i in hist:
    previous += i
    Sum_freq.append(previous)

previous

np.int64(17)

### 연습문제

In [17]:
# 1번문제
Day_Sell = np.array([18, 25, 33, 21, 28, 40, 15, 3, 9, 17, 22, 29, 38, 45, 11, 6, 31, 24, 27, 35, 12, 19, 39, 42, 7, 2, 20, 34, 26, 30])
Day_Sell

array([18, 25, 33, 21, 28, 40, 15,  3,  9, 17, 22, 29, 38, 45, 11,  6, 31,
       24, 27, 35, 12, 19, 39, 42,  7,  2, 20, 34, 26, 30])

In [ ]:
# 2번 문제
size = len(Day_Sell)
print(size)
Sorted_Day_Sell = np.sort(Day_Sell)
print(Sorted_Day_Sell)
hist, bins = np.histogram(Sorted_Day_Sell, [0,10,20,30,40,50])
print('구간별 데이터 수:', hist)
print('구간 경계:', bins)
# 분석과정
# Step 1. Day_Sell을 정렬 시킨뒤
# Step 2. 정해진 구간 별로 hist 및 bins 추출

30
[ 2  3  6  7  9 11 12 15 17 18 19 20 21 22 24 25 26 27 28 29 30 31 33 34
 35 38 39 40 42 45]
구간별 데이터 수: [5 6 9 7 3]
구간 경계: [ 0 10 20 30 40 50]


In [ ]:
# 3번 문제

# 절대도수
hist, bins = np.histogram(Sorted_Day_Sell, [0,10,20,30,40,50])
print('구간별 데이터 수:', hist)

구간별 데이터 수: [5 6 9 7 3]


In [38]:
# 3번 문제

# 상대도수
relative_freq = np.round(hist / np.sum(hist),3)
relative_freq

array([0.167, 0.2  , 0.3  , 0.233, 0.1  ])

In [ ]:
# 3번 문제

# 누적 도수
a = []
previous = 0

for i in Sorted_Day_Sell:
    previous += i
    a.append(previous)

previous

np.int64(708)

### 연습문제 - 2


In [ ]:
# 중앙값 계산

Crash = np.array([15129, 13836, 15738, 16300, 17605,16690, 16252, 17000, 16956, 17720, 17455, 15668])
print(Crash)

# 데이터 크기 계산

size = len(Crash)
print('데이터 크기:', size)

# 데이터 정렬
sorted_Crash = np.sort(Crash)
print('데이터 정렬:', sorted_Crash)

# 짝수인 경우..

if size % 2 == 0:
    a = (size // 2) -1
    b = a + 1
    median = (sorted_Crash[a] + sorted_Crash[b]) / 2
else:
    a = (size // 2)
    median = a
print('중앙값:', median)

[15129 13836 15738 16300 17605 16690 16252 17000 16956 17720 17455 15668]
데이터 크기: 12
데이터 정렬: [13836 15129 15668 15738 16252 16300 16690 16956 17000 17455 17605 17720]
중앙값: 16495.0


In [103]:
# 1 사분위수 계산

#Crash = np.array([15129, 13836, 15738, 16300, 17605,16690, 16252, 17000, 16956, 17720, 17455, 15668])
#print(Crash)

# 방법 1. 직접 계산
a = np.sort(Crash)
print(np.sort(Crash))
size = len(a) 
q1_pos = (size-1) * 0.25
b = int(np.floor(q1_pos))
f = q1_pos - b

# 보간
Q1 = round(a[b] + f *(a[b+1] - a[b]),0)
print('직접 계산 Q1:', Q1)

# 내장 함수 사용
print('내장 함수 사용:', round(np.quantile(a, 0.25),0))

[13836 15129 15668 15738 16252 16300 16690 16956 17000 17455 17605 17720]
직접 계산 Q1: 15720.0
내장 함수 사용: 15720.0


In [93]:
# 3 사분위수 계산

# 방법 1. 직접 계산
a = np.sort(Crash)
print(np.sort(Crash))
size = len(a) 
q3_pos = (size-1) * 0.75
b = int(np.floor(q3_pos))
f = q3_pos - b

# 보간
Q3 = round(a[b] + f *(a[b+1] - a[b]),0)
print('직접 계산 Q3:', Q3)

# 내장 함수 사용
print('내장 함수 사용:', round(np.quantile(a, 0.75),0))

# 표준편차
print('표준편차:', round(np.std(Crash)))
print('분산:', np.var(Crash))

[13836 15129 15668 15738 16252 16300 16690 16956 17000 17455 17605 17720]
직접 계산 Q3: 17114.0
내장 함수 사용: 17114.0
표준편차: 1089
분산: 1186603.7430555557


In [ ]:
# 절대도수, 상대도수, 누적도수

# 절대도수

hist, bins = np.histogram(Crash, [13000,14000,15000,16000,17000,18000])
print('구간별 데이터 수:', hist)
print('구간 경계:', bins)

# 상대도수

relative_freq = hist / np.sum(hist)
print(relative_freq)

# 누적도수

cum_freq = []

previous = 0

for i in hist:
    previous += i
    cum_freq.append(previous)

previous

구간별 데이터 수: [1 0 3 4 4]
구간 경계: [13000 14000 15000 16000 17000 18000]
[0.08333333 0.         0.25       0.33333333 0.33333333]


np.int64(12)

In [122]:
# 정리

hist, bins = np.histogram(Crash, [13000,14000,15000,16000,17000,18000])
print('구간별 데이터 수:', hist)
print('구간 경계:', bins)
print('3사분위수:',Q3)
print('1사분위수:',Q1)
print('4사분위수:', max(Crash))
print('사분위수 구간(IQR):', round((np.quantile(Crash, 0.7) - np.quantile(Crash, 0.25)), 0))
print('범위:', max(Crash) - min(Crash))
print('중앙값:', median)
print('표준편차:', round(np.std(Crash)))
print('분산:', round(np.var(Crash)))

구간별 데이터 수: [1 0 3 4 4]
구간 경계: [13000 14000 15000 16000 17000 18000]
3사분위수: 17114.0
1사분위수: 15720.0
4사분위수: 17720
사분위수 구간(IQR): 1266.0
범위: 3884
중앙값: 16495.0
표준편차: 1089
분산: 1186604


### 연습문제 -2 해설

구간별 데이터 수를 살펴보았을 때, 교통사고 건수는 연중 일정하게 유지되며 대부분의 달이 15,000~18,000 범위에 속한다.
즉, IQR 값과 표준편차를 통해 전체적으로 안정적인 분포를 보이는 것을 알수있다.
제공된 데이터 값을 살펴보면, 2월 교통사고 건수가 제일 적고 10월 교통사고 건수가 제일 많은 점을 볼 수 있다.
이와 같은 현상을 해석하고자 환경적 상황에 대한 이해가 필요하다.
2월의 경우 전체 12월에서 가장 적은 일 수(28일)를 가지고 있으며, 본격적으로 일몰 시각이 늦어지기 시작한다.
10월의 경우 본격적으로 일몰 시간이 빨라지기 시작한다.