# 기초 통계량의 이해
## 기초 통계량

### 데이터의 위치 분포를 나타내는 기초 통계량

In [6]:
import numpy as np

# 샘플 데이터
myarr = np.array([98,72,80,64,88,65,79,59,81,74])
myarr

# 총 도수
print('총 도수:', len(myarr))

# 최대, 최소, 합계 값
print('최대값:', np.max(myarr))
print('최소값:', np.min(myarr))
print('합계:', np.sum(myarr))

# 평균
print('평균:', np.average(myarr))

# 중앙값
print('중앙값:', np.median(myarr))

총 도수: 10
최대값: 98
최소값: 59
합계: 760
평균: 76.0
중앙값: 76.5


### 데이터의 위치 분포를 나타내는 기초 통계량 - 2

In [10]:
# 중앙값 직접구하기

size = len(myarr)
sorted_myarr = np.sort(myarr)
print('정렬된 값:', sorted_myarr)

# 짝수인 경우 가운데 두 수의 평균
if size % 2 ==0:
    p = (size // 2) - 1
    q = p + 1
    median = (sorted_myarr[p] + sorted_myarr[q]) / 2
else:
    p = size // 2
    median = sorted_myarr[p]

print('중앙값:', median)

정렬된 값: [59 64 65 72 74 79 80 81 88 98]
중앙값: 76.5


### 데이터의 위치 분포를 나타내는 기초 통계량 - 3

In [ ]:
# 1사분위수

myarr = np.array([98,72,80,64,88,65,79,59,81,74])
myarr

x = np.sort(myarr) # 데이터 정렬
print(np.sort(myarr))
n = len(x) # 총 도수(데이터 개수)
q1_pos = (n-1) * 0.25 # (1사분위수 위치 계산 식)
i = int(np.floor(q1_pos)) # 1사분위수는 데이터의 인덱스의 2번째, 3번째 사이에서 25%간 지점이다.
f = q1_pos - i

# 보간
Q1 = x[i] + f * (x[i+1] - x[i])
print('직접 계산한 1사분위수 (Q1):', Q1)

# Numpy 내장 함수
print('Numpy 내장 함수로 계산한 1사분위수:', np.quantile(myarr, 0.25))


[59 64 65 72 74 79 80 81 88 98]
직접 계산한 1사분위수 (Q1): 66.75
Numpy 내장 함수로 계산한 1사분위수: 66.75


In [ ]:
# 3사분위수

x = np.sort(myarr) # 데이터 정렬
n = len(x) # 총 도수(데이터 개수)
q3_pos = (n-1) * 0.75 # (1사분위수 위치 계산 식, 아래 인덱스)
i = int(np.floor(q3_pos)) # 1사분위수는 데이터의 2번째, 3번째 사이에서 75%간 지점이다.
f = q3_pos - i  # 소수 부분(보간비율)

# 보간
Q3 = x[i] + f * (x[i+1] - x[i])
print('직접 계산한 1사분위수 (Q1):', Q1)

# Numpy 내장 함수
print('Numpy 내장 함수로 계산한 1사분위수:', np.quantile(myarr, 0.75))

Numpy 내장 함수로 계산한 1사분위수: 80.75


### 데이터의 범위 산포를 나타내는 기초통계량

In [19]:
# 데이터 구간

print('데이터 구간:', np.max(myarr) - np.min(myarr))

데이터 구간: 39


In [41]:
# 사분위수 구간(IQR)

print('사분위수 구간:', np.quantile(myarr, 0.25))
print('표준편차:', np.std(myarr))
print('분산:', np.var(myarr))

사분위수 구간: 66.75
표준편차: 11.189280584559492
분산: 125.2


### 2차원 배열의 기초 통계량 - 1

In [ ]:
# 각 열끼리 계산(세로연산)
mydata = np.array([[98,72,80,64,88],
                    [65,79,59,81,74]])

s1 = np.sum(mydata, axis=0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([163, 151, 139, 145, 162])

In [45]:
# 각 행끼리 계산(가로연산)
mydata = np.array([[98,72,80,64,88],
                    [65,79,59,81,74]])

s1 = np.sum(mydata, axis=1)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([402, 358])

### 연습문제

In [ ]:
alpha = [88, 92, 76, 100, 95, 81, 79, 98, 85, 87]
brabo = [65, 99, 78, 72, 80, 91, 75, 82, 89, 70]

# 1번
print('alpha도수:',len(alpha))
print('brabo도수:',len(brabo))
print('-' * 50)
# 2번
print('alpha평균:',np.average(alpha))
print('brabo평균:',np.average(brabo))
print('-' * 50)
# 3번
print('alpha표준편차:',np.std(alpha))
print('brabo표준편차:',np.std(brabo))
print('-' * 50)
# 4번
print('alpha최소값:', min(alpha))
print('alpha최대값:', max(alpha))
print('-' * 50)
print('brabo최소값:', min(brabo))
print('brabo최대값:', max(brabo))
print('-' * 50)
# 5번
print('alpha1사분위 수:', np.quantile(alpha, 0.25))
print('alpha2사분위 수:', np.quantile(alpha, 0.5))
print('alpha3사분위 수:', np.quantile(alpha, 0.75))
print('-' * 50)
# 직접 코딩
size = len(alpha)
sorted_alpha = np.sorted(alpha)


print('-' * 50)
print('brabo1사분위 수:', np.quantile(brabo, 0.25))
print('brabo2사분위 수:', np.quantile(brabo, 0.5))
print('brabo3사분위 수:', np.quantile(brabo, 0.75))
print('-' * 50)

alpha도수: 10
brabo도수: 10
--------------------------------------------------
alpha평균: 88.1
brabo평균: 80.1
--------------------------------------------------
alpha표준편차: 7.7
brabo표준편차: 9.924212815130478
--------------------------------------------------
alpha최소값: 76
alpha최대값: 100
--------------------------------------------------
brabo최소값: 65
brabo최대값: 99
--------------------------------------------------
alpha1사분위 수: 82.0
alpha2사분위 수: 87.5
alpha3사분위 수: 94.25
--------------------------------------------------
brabo1사분위 수: 72.75
brabo2사분위 수: 79.0
brabo3사분위 수: 87.25
--------------------------------------------------
